language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.5 --use-mirrors
  - DJANGO=django==1.4.5 --use-mirrors
  - DJANGO=django==1.3.7 --use-mirrors

install:
  - pip install $DJANGO

script:
  - "`which django-admin.py` test post_office --settings=post_office.test_settings --pythonpath=."
