language: python
dist: bionic

matrix:
  fast_finish: true
  include:
    # Python 3.5
    - python: 3.5
      env: TOXENV=py35-django22

    # Python 3.6
    - python: 3.6
      env: TOXENV=py36-django22,py36-django30

    # Python 3.7
    - python: 3.7
      env: TOXENV=py37-django22,py37-django30,py37-preventxss

    # Python 3.8
    - python: 3.8
      env: TOXENV=py38-django22,py38-django30

    # Django Master
    - python: 3.6
      env: TOXENV=py36-djangomaster
    - python: 3.7
      env: TOXENV=py37-djangomaster
    - python: 3.8
      env: TOXENV=py38-djangomaster

  allow_failures:
    - python: 3.6
      env: TOXENV=py36-djangomaster
    - python: 3.7
      env: TOXENV=py37-djangomaster
    - python: 3.8
      env: TOXENV=py38-djangomaster

# before_install:
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm

install:
  - pip install tox-travis

script:
  - tox
