language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.4.9
  - DJANGO=1.5.5
  - DJANGO=1.6.1

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.9

before_install:
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - pip install Django==$DJANGO django-jsonfield

script:
  - "python post_office/tests/runtests.py"
